### Developing first neural network model

In [1]:
 # importing required libraries
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

In [2]:
# set random seed
np.random.seed(42)

### Forward Propagation without backward propagation

In [3]:
#load input
# creating the input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
print ('\n Input:')
print(X)


# creating the output array
y=np.array([[1],[1],[0]])
print ('\n Actual Output:')
print(y)

# defining the Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

# derivative of Sigmoid Function
def derivatives_sigmoid(x):
    
    return x * (1 - x)

# initializing the variables
epoch=5000 # number of training iterations
lr=0.1 # learning rate

inputlayer_neurons = X.shape[1] # number of features in data set
hiddenlayer_neurons = 3 # number of hidden layers neurons
output_neurons = 1 # number of neurons at output layer

# initializing weight and bias
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

# training the model
for i in range(epoch):

    #Forward Propogation y= x.w
    hidden_layer_input1=np.dot(X,wh) #weighted ip
    
    z=hidden_layer_input1 + bh # z= wt+b
    # g(z)=1/1+e^(-z)
    
    hiddenlayer_activations = sigmoid(z)
    
    ## op of hidden layer is input of next layer: HL, OL 
    
    output_layer_input1=np.dot(hiddenlayer_activations,wout) #weighted ip
    output_layer_input= output_layer_input1+ bout # z= wt+b
    output = sigmoid(output_layer_input) # g(z)=1/1+e^(-z)

print ('\n Output from the model:')
print (output)



 Input:
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]

 Actual Output:
[[1]
 [1]
 [0]]

 Output from the model:
[[0.78143891]
 [0.79362068]
 [0.76681588]]


### Importance of Backward Propagation

In [4]:
for i in range(epoch):
    #Forward Propogation y= x.w
    hidden_layer_input1=np.dot(X,wh) #weighted ip
    
    z=hidden_layer_input1 + bh # z= wt+b
    # g(z)=1/1+e^(-z)
    
    hiddenlayer_activations = sigmoid(z)
    
    ## op of hidden layer is input of next layer: HL, OL 
    
    output_layer_input1=np.dot(hiddenlayer_activations,wout) #weighted ip
    output_layer_input= output_layer_input1+ bout # z= wt+b
    output = sigmoid(output_layer_input) # g(z)=1/1+e^(-z)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)  #Then compute change factor(delta) at the output layer, dependent on the gradient of error multiplied by the slope of output layer activation
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
print ('\n Output from the model:')
print (output)



 Output from the model:
[[0.98404531]
 [0.9745495 ]
 [0.03606094]]


In [5]:
# creating the input array
X = np.array([[1, 0, 0, 0], [1, 0, 1, 1], [0, 1, 0, 1]])

print("Input:\n", X)

# shape of input array
print("\nShape of Input:", X.shape)

Input:
 [[1 0 0 0]
 [1 0 1 1]
 [0 1 0 1]]

Shape of Input: (3, 4)


In [6]:

# converting the input in matrix form
X = X.T
print("Input in matrix form:\n", X)

# shape of input matrix
print("\nShape of Input Matrix:", X.shape)

Input in matrix form:
 [[1 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]

Shape of Input Matrix: (4, 3)


In [7]:
# creating the output array
y = np.array([[1], [1], [0]])

print("Actual Output:\n", y)

# output in matrix form
y = y.T

print("\nOutput in matrix form:\n", y)

# shape of input array
print("\nShape of Output:", y.shape)

Actual Output:
 [[1]
 [1]
 [0]]

Output in matrix form:
 [[1 1 0]]

Shape of Output: (1, 3)


In [8]:
inputLayer_neurons = X.shape[0]  # number of features in data set
hiddenLayer_neurons = 3  # number of hidden layers neurons
outputLayer_neurons = 1  # number of neurons at output layer


In [9]:
# initializing weight
# Shape of weights_input_hidden should number of neurons at input layer * number of neurons at hidden layer
weights_input_hidden = np.random.uniform(size=(inputLayer_neurons, hiddenLayer_neurons))

# Shape of weights_hidden_output should number of neurons at hidden layer * number of neurons at output layer
weights_hidden_output = np.random.uniform(
    size=(hiddenLayer_neurons, outputLayer_neurons)
)

In [10]:
# shape of weight matrix
weights_input_hidden.shape, weights_hidden_output.shape# We are using sigmoid as an activation function so defining the sigmoid function here

((4, 3), (3, 1))

In [11]:

# We are using sigmoid as an activation function so defining the sigmoid function here

# defining the Sigmoid Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [12]:
# hidden layer activations

hiddenLayer_linearTransform = np.dot(weights_input_hidden.T, X)
hiddenLayer_activations = sigmoid(hiddenLayer_linearTransform)

In [13]:
# calculating the output
outputLayer_linearTransform = np.dot(weights_hidden_output.T, hiddenLayer_activations)
output = sigmoid(outputLayer_linearTransform)

In [14]:
# output
output

array([[0.65638996, 0.71678677, 0.70375011]])